services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - mysql
    volumes:
      - ./services/grafana/data:/var/lib/grafana
      - ./services/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - traefik_net
      - grafana_net
      
      - prometheus_net
      - mysql_net
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} 
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=${GRAFANA_MYSQL_PASSWORD}
    labels:
      - "traefik.enable=true"

      # Redirect http to https
      - "traefik.http.routers.grafana-http.rule=Host(`${GRAFANA_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.grafana-http.entrypoints=http"
      - "traefik.http.routers.grafana-http.middlewares=redirect-to-https"
      # Https handler
      - "traefik.http.routers.grafana-https.rule=Host(`${GRAFANA_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.grafana-https.entrypoints=https"
      - "traefik.http.routers.grafana-https.tls=true"
      - "traefik.http.routers.grafana-https.tls.certresolver=cloudflare"

      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
