services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower:latest

    command: --interval ${WATCHTOWER_DELAY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
