services:
  mysql:
    build: 
      context: services/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    networks:
      - mysql_net
      - public_net
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - PANEL_MYSQL_PASSWORD=${PANEL_MYSQL_PASSWORD}
      - EXPORTER_MYSQL_PASSWORD=${EXPORTER_MYSQL_PASSWORD}
      - GRAFANA_MYSQL_PASSWORD=${GRAFANA_MYSQL_PASSWORD}
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -h localhost --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 
