services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - mysql_exporter
      - redis_exporter
      - node_exporter
    volumes:
      - ./services/prometheus/data/config.yml:/etc/prometheus/prometheus.yml
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9090 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
    command:
      - "--mysqld.username=exporter:${EXPORTER_MYSQL_PASSWORD}"
      - "--mysqld.address=mysql:3306"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9104 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis_exporter:
    build: 
      context: services/prometheus
      dockerfile: redis_exporter_Dockerfile
    container_name: redis_exporter
    restart: unless-stopped
    depends_on:
      - redis    
    networks:
      - traefik
    environment:
      - HEALTHCHECK_PORT=9121
      - HEALTHCHECK_PATH=/metrics
    labels:
      - "traefik.enable=false"
    command:
     - "--redis.addr=redis://redis:6379"
     - "--redis.password=${REDIS_PASSWORD}"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    #volumes:
    #  - '/:/host:ro,rslave'
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
    command:
      - '--path.rootfs=/host'
    pid: host
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9100 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
