services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./services/traefik/lets_encrypt:/lets_encrypt"
      - "./services/traefik/logs:/logs"
    networks:
      - traefik_net
      - public_net

      - exporters_net # Traefik prometheus exporter
    ports:
      - "80:80"                                  # HTTP
      - "443:443"                                # HTTPS
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_KEY}
      - TZ=${TRAEFIK_TIMEZONE}
    labels:
      - "traefik.http.middlewares.redirect-play-subdomain-middleware.redirectregex.regex=^https://${PLAY_SUBDOMAIN}.${DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirect-play-subdomain-middleware.redirectregex.replacement=https://${DOMAIN}/"
      - "traefik.http.middlewares.redirect-play-subdomain-middleware.redirectregex.permanent=true"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      # Redirect http to https (redirect play subdomain)
      - "traefik.http.routers.redirect-play-subdomain-http.rule=Host(`${PLAY_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.redirect-play-subdomain-http.entrypoints=http"
      - "traefik.http.routers.redirect-play-subdomain-http.middlewares=redirect-to-https"
      # Https handler (redirect play subdomain)
      - "traefik.http.routers.redirect-play-subdomain-https.rule=Host(`${PLAY_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.redirect-play-subdomain-https.entrypoints=https"
      - "traefik.http.routers.redirect-play-subdomain-https.middlewares=redirect-play-subdomain-middleware"
      - "traefik.http.routers.redirect-play-subdomain-https.service=noop@internal"
      - "traefik.http.routers.redirect-play-subdomain-https.tls=true"
      - "traefik.http.routers.redirect-play-subdomain-https.tls.certresolver=cloudflare"  
    command:
      - "--entrypoints.http.address=:80"           # HTTP
      - "--entrypoints.https.address=:443"         # HTTPS
      - "--entrypoints.prometheus.address=:9103"   # Prometheus

      - "--providers.docker=true"

      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_API_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/lets_encrypt/acme.json"

      - "--accesslog=true" 
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.format=common" 
      - "--accesslog.fields.names.Method=true" 
      - "--accesslog.fields.names.Path=true"
      - "--accesslog.fields.names.Host=true"
      - "--accesslog.fields.names.RequestCount=true"
      - "--accesslog.fields.names.ResponseTime=true"

      - "--log.format=common" 
      - "--log.level=${TRAEFIK_LOG_LEVEL}"

      - "--global.sendanonymoususage=${TRAEFIK_SEND_ANOYMOUS_USAGE}"

      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=prometheus"

      - "--experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp"
      - "--experimental.plugins.cloudflarewarp.version=v1.3.3"

      - "--providers.docker.network=traefik_net"
