services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:latest

    networks:
      - traefik
    command:
      - "--entrypoints.http.address=:80"           # HTTP
      - "--entrypoints.https.address=:443"         # HTTPS
      - "--entrypoints.mysql.address=:3306"        # MySQL
      - "--entrypoints.redis.address=:6379"        # Redis
      - "--entrypoints.prometheus.address=:9103"   # Prometheus
      - "--entrypoints.wings_sftp.address=:${WINGS_SFTP_PORT}"

      - "--providers.docker=true"

      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_API_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/lets_encrypt/acme.json"

      - "--accesslog=true" 
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.format=common" 
      - "--accesslog.fields.names.Method=true" 
      - "--accesslog.fields.names.Path=true"
      - "--accesslog.fields.names.Host=true"
      - "--accesslog.fields.names.RequestCount=true"
      - "--accesslog.fields.names.ResponseTime=true"

      - "--log.filepath=/logs/traefik.log"
      - "--log.format=common" 
      - "--log.level=${TRAEFIK_LOG_LEVEL}"

      - "--global.sendanonymoususage=${TRAEFIK_SEND_ANOYMOUS_USAGE}"

      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=prometheus"
    labels:
      - "traefik.http.middlewares.redirect-play-subdomain-middleware.redirectregex.regex=^https://${PLAY_SUBDOMAIN}.${DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirect-play-subdomain-middleware.redirectregex.replacement=https://${DOMAIN}/"
      - "traefik.http.middlewares.redirect-play-subdomain-middleware.redirectregex.permanent=true"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      - "traefik.http.routers.redirect-play-subdomain.rule=Host(`${PLAY_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.redirect-play-subdomain.entrypoints=https"
      - "traefik.http.routers.redirect-play-subdomain.middlewares=redirect-to-https,redirect-play-subdomain-middleware"
      - "traefik.http.routers.redirect-play-subdomain.service=noop@internal"
      - "traefik.http.routers.redirect-play-subdomain.tls=true"
      - "traefik.http.routers.redirect-play-subdomain.tls.certresolver=cloudflare"

      - "traefik.http.routers.redirect-to-https.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-to-https.entrypoints=http"
      - "traefik.http.routers.redirect-to-https.middlewares=redirect-to-https"
      - "traefik.http.routers.redirect-to-https.service=noop@internal"
      - "traefik.http.routers.redirect-to-https.tls=false"
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_KEY}
      - TZ=${TRAEFIK_TIMEZONE}
    ports:
      - "80:80"                                  # HTTP
      - "443:443"                                # HTTPS
      - "3306:3306"                              # MySQL
      - "6379:6379"                              # Redis
      - "${WINGS_SFTP_PORT}:${WINGS_SFTP_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./services/traefik/lets_encrypt:/lets_encrypt"
      - "./services/traefik/logs:/logs"
