services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: portainer/portainer-ce:lts

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./services/portainer/data:/data"
    networks:
      - traefik
