services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./services/redis/data:/data
    networks:
      - redis_net
      - public_net
    ports:
      - 127.0.0.1:6379:6379
    labels:
      - "traefik.enable=false"  
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}   
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping", "||" , "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
