services:
  wings:
    image: ghcr.io/loki-101/cwings:latest
    container_name: wings
    restart: unless-stopped
    depends_on:
      - panel
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "./services/wings/config:/etc/pterodactyl"
      - "/srv/pterodactyl:/srv/pterodactyl"
      - "/var/lib/pterodactyl:/var/lib/pterodactyl"
      - "/var/log/pterodactyl:/var/log/pterodactyl"
      - "/tmp/pterodactyl:/tmp/pterodactyl"
    networks:
      - traefik_net
      - wings_net
    ports:
      - ${WINGS_SFTP_PORT}:2022
    environment:
      TZ: "${WINGS_TIMEZONE}"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    labels:
      - "traefik.enable=true"

      # Web

      # Redirect http to https
      - "traefik.http.routers.wings-http.rule=Host(`${WINGS_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wings-http.entrypoints=http"
      - "traefik.http.routers.wings-http.middlewares=redirect-to-https"
      # Https handler
      - "traefik.http.routers.wings-https.rule=Host(`${WINGS_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.wings-https.entrypoints=https"
      - "traefik.http.routers.wings-https.tls=true"
      - "traefik.http.routers.wings-https.tls.certresolver=cloudflare"

      - "traefik.http.services.wings.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
